Repository ezsystems/ezplatform-rest, pull requests merged in 2019-12, with the labels that each got.

#30 [Composer] Added missing requirements for PHP extensions
  composer.json
Labels: Bug, DX

#29 EZP-31125: Added TranslatedName to Content/ContentInfo in REST response
  src/bundle/Resources/config/value_object_visitors.yml
  src/lib/Server/Output/ValueObjectVisitor/RestContent.php
  tests/lib/Server/Output/ValueObjectVisitor/RestContentTest.php
Labels: Improvement, QA approved

#18 Install latest dependencies
  composer.json
Labels: Ready for review

#31 [Tests] Refactored REST SearchViewTest and provided more payloads
  tests/bundle/Functional/SearchViewTest.php
Labels: Improvement, Ready for review

#34 EZP-31078: Enhanced Content Type Value Object
  src/lib/Server/Controller/ContentType.php
  src/lib/Server/Output/ValueObjectVisitor/ContentTypeList.php
  tests/lib/Server/Input/Parser/ContentCreateTest.php
  tests/lib/Server/Input/Parser/FieldDefinitionUpdateTest.php
  tests/lib/Server/Input/Parser/UserCreateTest.php
  tests/lib/Server/Input/Parser/UserGroupCreateTest.php
  tests/lib/Server/Output/ValueObjectVisitor/ContentTypeListTest.php
Labels: Bug
