Repository ezsystems/ezplatform-rest, pull requests merged in 2019-06, with the labels that each got.

#10 [Composer] Set minimum-stability and prefer-stable
  composer.json
Labels: Improvement

#9 EZP-30517: Dropped obsolete RichTextProcessor
  src/bundle/Resources/config/services.yml
  src/lib/FieldTypeProcessor/RichTextProcessor.php
  tests/lib/FieldTypeProcessor/RichTextProcessorTest.php
Labels: Bug, Ready for MERGE

#12 Upgraded tests to PHPUnit 8 and fixed executing integration tests on Travis
  .travis.yml
  composer.json
  tests/bundle/DependencyInjection/Compiler/OutputVisitorPassTest.php
  tests/bundle/EventListener/ResponseListenerTest.php
  tests/bundle/Functional/SearchViewTest.php
  tests/bundle/Functional/SessionTest.php
  tests/bundle/Functional/TestCase.php
  tests/bundle/Routing/OptionsLoader/MapperTest.php
  tests/bundle/Routing/OptionsLoader/RouteCollectionMapperTest.php
  tests/lib/FieldTypeProcessor/BinaryInputProcessorTest.php
  tests/lib/Input/FieldTypeParserTest.php
  tests/lib/Output/Generator/FieldTypeHashGeneratorBaseTest.php
  tests/lib/Server/Output/ValueObjectVisitor/BookmarkListTest.php
  tests/lib/Server/Output/ValueObjectVisitor/CachedValueTest.php
  tests/lib/Server/Output/ValueObjectVisitor/RestFieldDefinitionTest.php
  tests/lib/Server/Output/ValueObjectVisitor/VersionInfoTest.php
  tests/lib/Server/Output/ValueObjectVisitor/VersionTest.php
  tests/lib/Server/Security/CsrfTokenManagerTest.php
  tests/lib/Server/Security/RestLogoutHandlerTest.php
  tests/lib/Server/Security/RestSessionBasedAuthenticatorTest.php
Labels: Bug

#11 EZP-30685: As a Developer I want to easier generate attribute/value elements in Value Object Visitors
  src/lib/Output/Generator.php
  tests/lib/Output/Generator/JsonTest.php
  tests/lib/Output/Generator/XmlTest.php
  tests/lib/Output/Generator/_fixtures/testGeneratorStartEndAttribute.xml
  tests/lib/Output/Generator/_fixtures/testGeneratorStartEndValueElement.xml
Labels: DX, Feature
