Repository ezsystems/ezplatform-rest, pull requests merged in 2019-11, with the labels that each got.

#23 EZP-31115: Added `isHidden` flag to `ContentInfo` in REST response
  src/lib/Server/Output/ValueObjectVisitor/RestContent.php
  tests/lib/Server/Output/ValueObjectVisitor/RestContentTest.php
Labels: Improvement, QA approved

#26 EZP-31108: Provided common PHP CS Fixer configuration for internal use
  .php_cs
  composer.json
Labels: Improvement, Ready for review

#24 EZP-31122: Added explicitlyHidden flag to Location in REST response
  src/lib/Server/Output/ValueObjectVisitor/RestLocation.php
  tests/lib/Server/Output/ValueObjectVisitor/RestLocationRootNodeTest.php
  tests/lib/Server/Output/ValueObjectVisitor/RestLocationTest.php
Labels: Improvement, QA approved

#25 EZP-31021: Revised exception and command messages
  src/bundle/DependencyInjection/Compiler/FieldTypeProcessorPass.php
  src/bundle/DependencyInjection/Compiler/InputHandlerPass.php
  src/bundle/DependencyInjection/Compiler/InputParserPass.php
  src/bundle/DependencyInjection/Compiler/OutputVisitorPass.php
  src/bundle/DependencyInjection/Compiler/ValueObjectVisitorPass.php
  src/bundle/RequestParser/Router.php
  src/lib/FieldTypeProcessorRegistry.php
  src/lib/Input/ParserTools.php
  src/lib/Input/ParsingDispatcher.php
  src/lib/Output/Exceptions/NoVisitorFoundException.php
  src/lib/Output/Generator.php
  src/lib/Output/Generator/Json/FieldTypeHashGenerator.php
  src/lib/Output/Generator/Xml/FieldTypeHashGenerator.php
  src/lib/Output/ValueObjectVisitor.php
  src/lib/RequestParser/Pattern.php
  src/lib/Server/Controller/BinaryContent.php
  src/lib/Server/Controller/Content.php
  src/lib/Server/Controller/ContentType.php
  src/lib/Server/Controller/Location.php
  src/lib/Server/Controller/ObjectState.php
  src/lib/Server/Controller/User.php
  src/lib/Server/Input/Parser/ContentCreate.php
  src/lib/Server/Input/Parser/ContentTypeCreate.php
  src/lib/Server/Input/Parser/ContentTypeGroupInput.php
  src/lib/Server/Input/Parser/ContentTypeUpdate.php
  src/lib/Server/Input/Parser/ContentUpdate.php
  src/lib/Server/Input/Parser/Criterion/Field.php
  src/lib/Server/Input/Parser/LocationCreate.php
  src/lib/Server/Input/Parser/RelationCreate.php
  src/lib/Server/Input/Parser/SortClause/DataKeyValueObjectClass.php
  src/lib/Server/Input/Parser/SortClause/Field.php
  src/lib/Server/Input/Parser/UserCreate.php
  src/lib/Server/Input/Parser/UserGroupCreate.php
  src/lib/Server/Input/Parser/UserGroupUpdate.php
  src/lib/Server/Input/Parser/UserUpdate.php
  src/lib/Server/Input/Parser/VersionUpdate.php
  src/lib/Server/Output/ValueObjectVisitor/RestContentTypeBase.php
  src/lib/Server/Output/ValueObjectVisitor/RestRelation.php
  tests/bundle/Functional/ContentTest.php
  tests/bundle/RequestParser/RouterTest.php
  tests/lib/Server/Input/Parser/ContentCreateTest.php
  tests/lib/Server/Input/Parser/ContentTypeCreateTest.php
  tests/lib/Server/Input/Parser/ContentTypeGroupInputTest.php
  tests/lib/Server/Input/Parser/ContentTypeUpdateTest.php
  tests/lib/Server/Input/Parser/ContentUpdateTest.php
  tests/lib/Server/Input/Parser/LocationCreateTest.php
  tests/lib/Server/Input/Parser/PolicyCreateTest.php
  tests/lib/Server/Input/Parser/PolicyUpdateTest.php
  tests/lib/Server/Input/Parser/RelationCreateTest.php
  tests/lib/Server/Input/Parser/SortClause/DataKeyValueObjectClassTest.php
  tests/lib/Server/Input/Parser/SortClause/FieldTest.php
  tests/lib/Server/Input/Parser/UserCreateTest.php
  tests/lib/Server/Input/Parser/UserGroupCreateTest.php
  tests/lib/Server/Input/Parser/UserGroupUpdateTest.php
  tests/lib/Server/Input/Parser/UserUpdateTest.php
  tests/lib/Server/Input/Parser/VersionUpdateTest.php
Labels: Ready for MERGE
