Repository ezsystems/ezplatform-rest, pull requests merged in 2020-10, with the labels that each got.

#54 EZP-31875: Implemented JWT authentication Controller
  composer.json
  src/bundle/Resources/config/default_settings.yml
  src/bundle/Resources/config/input_parsers.yml
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/security.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/value_object_visitors.yml
  src/lib/Server/Controller/JWT.php
  src/lib/Server/Input/Parser/JWTInput.php
  src/lib/Server/Output/ValueObjectVisitor/JWT.php
  src/lib/Server/Security/EventListener/SecurityListener.php
  src/lib/Server/Values/JWT.php
  src/lib/Server/Values/JWTInput.php
  tests/lib/Server/Input/Parser/JWTInputTest.php
  tests/lib/Server/Output/ValueObjectVisitor/JWTTest.php
  tests/lib/Server/Security/SecurityListenerTest.php
Labels: DX, Feature, Ready for QA

#55 EZP-27458: Aggregation API
  src/bundle/Resources/config/input_parsers.yml
  src/bundle/Resources/config/value_object_visitors.yml
  src/lib/Output/DelegateValueObjectVisitor.php
  src/lib/Server/Input/Parser/Aggregation/AbstractRangeAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/AbstractStatsAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/AbstractTermAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/ContentTypeGroupTermAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/ContentTypeTermAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/DateMetadataRangeAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/Field/AuthorTermAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/Field/CheckboxTermAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/Field/CountryTermAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/Field/DateRangeAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/Field/DateTimeRangeAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/Field/FloatRangeAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/Field/FloatStatsAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/Field/IntegerRangeAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/Field/IntegerStatsAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/Field/KeywordTermAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/Field/SelectionTermAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/Field/TimeRangeAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/LanguageTermAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/Location/SubtreeTermAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/ObjectStateTermAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/Range/AbstractRangeParser.php
  src/lib/Server/Input/Parser/Aggregation/Range/DateTimeRangeParser.php
  src/lib/Server/Input/Parser/Aggregation/Range/FloatRangeParser.php
  src/lib/Server/Input/Parser/Aggregation/Range/IntRangeParser.php
  src/lib/Server/Input/Parser/Aggregation/RawRangeAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/RawStatsAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/RawTermAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/SectionTermAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/UserMetadataTermAggregationParser.php
  src/lib/Server/Input/Parser/Aggregation/VisibilityTermAggregationParser.php
  src/lib/Server/Input/Parser/Criterion.php
  src/lib/Server/Input/Parser/Query.php
  src/lib/Server/Output/ValueObjectVisitor/Author.php
  src/lib/Server/Output/ValueObjectVisitor/ContentType.php
  src/lib/Server/Output/ValueObjectVisitor/Language.php
  src/lib/Server/Output/ValueObjectVisitor/ObjectState.php
  src/lib/Server/Output/ValueObjectVisitor/Range.php
  src/lib/Server/Output/ValueObjectVisitor/RangeAggregationResult.php
  src/lib/Server/Output/ValueObjectVisitor/RestExecutedView.php
  src/lib/Server/Output/ValueObjectVisitor/StatsAggregationResult.php
  src/lib/Server/Output/ValueObjectVisitor/TermAggregationResult.php
  src/lib/Server/Output/ValueObjectVisitor/User.php
  src/lib/Server/Output/ValueObjectVisitor/UserGroup.php
Labels: Feature

#57 EZP-31039: Skip requirement of sort params when updating Location via REST
  src/lib/Server/Input/Parser/LocationUpdate.php
  tests/lib/Server/Input/Parser/LocationUpdateTest.php
Labels: Improvement, QA approved
