Repository ezsystems/ezplatform-rest, pull requests merged in 2020-03, with the labels that each got.

#39 EZP-31080: Created missing search Criterions
  src/bundle/Resources/config/input_parsers.yml
  src/lib/Server/Input/Parser/Criterion/IsUserBased.php
  src/lib/Server/Input/Parser/Criterion/IsUserEnabled.php
  src/lib/Server/Input/Parser/Criterion/ObjectStateIdentifier.php
  src/lib/Server/Input/Parser/Criterion/SectionIdentifier.php
  src/lib/Server/Input/Parser/Criterion/UserEmail.php
  src/lib/Server/Input/Parser/Criterion/UserId.php
  src/lib/Server/Input/Parser/Criterion/UserLogin.php
  tests/bundle/Functional/SearchView/Criterion/IsUserBasedTest.php
  tests/bundle/Functional/SearchView/Criterion/IsUserEnabledTest.php
  tests/bundle/Functional/SearchView/Criterion/ObjectStateIdentifierTest.php
  tests/bundle/Functional/SearchView/Criterion/SectionIdentifierTest.php
  tests/bundle/Functional/SearchView/Criterion/UserEmailTest.php
  tests/bundle/Functional/SearchView/Criterion/UserIdTest.php
  tests/bundle/Functional/SearchView/Criterion/UserLoginTest.php
  tests/bundle/Functional/SearchView/SearchCriterionTestCase.php
  tests/bundle/Functional/SearchView/SearchViewTest.php
  tests/bundle/Functional/SearchView/SearchViewTestCase.php
Labels: Feature, QA approved

#40 EZP-31415: Impl. input parser for Sibling criterion
  src/bundle/Resources/config/input_parsers.yml
  src/lib/Server/Input/Parser/Criterion/Sibling.php
  tests/lib/Server/Input/Parser/Criterion/SiblingTest.php
Labels: Feature, QA approved

#43 Adjusted unit tests to recent changes
  tests/lib/Server/Output/ValueObjectVisitor/RestExecutedViewTest.php
Labels: Bug

#45 EZP-31007: Replaced ezpublish-kernel with ezplatform-kernel
  composer.json
Labels: Improvement

#46 EZP-31531: Used hautelook/templated-uri-bundle instead of our fork
  composer.json
Labels: Improvement, Ready for review
