Repository ezsystems/ezplatform-rest, pull requests merged in 2020-02, with the labels that each got.

#36 [Travis] Changed user running REST tests to root
  .travis.yml
Labels: Ready for review

#37 Added totalCount attribute to REST ContentList response
  src/lib/Server/Output/ValueObjectVisitor/ContentList.php
  src/lib/Server/Values/ContentList.php
  tests/lib/Server/Output/ValueObjectVisitor/ContentListTest.php
Labels: QA approved

#38 EZP-31298: Made non verbose exception messages in REST responses
  src/lib/Server/Output/ValueObjectVisitor/Exception.php
  tests/lib/Server/Output/ValueObjectVisitor/ExceptionTest.php
Labels: Bug, QA approved
